# Generated by Django 5.2 on 2025-04-22 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('preparation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preptask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'KitchenStaff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preptask',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['KitchenStaff', 'DeliveryStaff']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation.preptask'),
        ),
    ]
