# Generated by Django 5.2 on 2025-04-27 13:18

from django.db import migrations, models
from django.utils.timezone import now  # <-- Added this import

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_amount_alter_invoice_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='method',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_pdf',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),  # fixed default
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=now),  # fixed default
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('Unpaid', 'Unpaid'),
                    ('Paid', 'Paid'),
                    ('Partially Paid', 'Partially Paid')
                ],
                default='Unpaid',
                max_length=20
            ),
        ),
    ]
