# Generated by Django 5.2 on 2025-05-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_invoice_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
