# Generated by Django 5.2 on 2025-05-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_status'),
        ('payments', '0011_paymentmethod_remove_invoice_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Unpaid', max_length=15),
        ),
    ]
