# Generated by Django 5.2 on 2025-04-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_terms', models.TextField()),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Custom', 'Custom')], default='Weekly', max_length=20)),
                ('next_delivery_date', models.DateField()),
                ('base_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_details', to='orders.order')),
            ],
        ),
    ]
